---
- name: Update and upgrade apt packages
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3.12

  become: true
  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: "yes"
  