---
- name: install vsftpd
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3.12  ## specify the python interpreter thats already in the machine to avoid the warning when running the playbook

  become: true
  tasks:
    - name: Install vsftpd
      apt:
        name: vsftpd
        state: present
        update_cache: true
        
    - name: Change listen=NO to listen=YES in vsftpd.conf
      lineinfile:
        path: /etc/vsftpd.conf
        regexp: '^listen=NO'
        line: 'listen=YES'

    - name: Uncomment write_enable=YES in vsftpd.conf
      lineinfile:
        path: /etc/vsftpd.conf
        regexp: '^#write_enable=YES'
        line: 'write_enable=YES'
        
    - name: Restart vsftpd service
      service:
        name: vsftpd
        state: restarted
        